Module 2 Awesome books plain JS with objects
abrormukimov/awesomebooks pull request #2
Opened 2021-08-10 12:16 UTC by abrormukimov

# Awesome books

## In this project, we implemented:

- UI of the website using only HTML (without CSS);
- local storage (to store books);
- add and remove books functionality from the library;

2021-08-10 13:29 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check comments below for this review

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 13:29 UTC, vichuge commented on index.html
> +    <input type="submit" class="add-btn" value="Add">
- [ ] The Add button could be aligned to right. Please add it. 🐶

2021-08-10 13:29 UTC, vichuge commented on index.html
> +  </ul>
- [ ] It looks like the project could be matched more according to the [template](https://github.com/microverseinc/curriculum-javascript/blob/bb245ca8a9d3bb04ebefbbd45e800764e1fc5f74/books/images/awesome_books_core_elements.png). Please, add some books and add the table. 


| your project | template |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/128873427-3c4427e3-32c2-49dc-9de2-7c4545b084e8.png) | ![image](https://user-images.githubusercontent.com/20563252/128873695-e729a30d-d70e-4e0a-84a8-50123745321f.png) |

2021-08-10 13:55 UTC, abrormukimov commented on index.html
> +  </ul>
<img width="1174" alt="Screen Shot 2021-08-10 at 18 52 26" src="https://user-images.githubusercontent.com/59091200/128879426-b9d41a19-2f08-4ae0-a434-ce88903f7662.png">

This is the requirement that says we need to use plain HTML without any style yet. We are at the very beginning of the project.

2021-08-10 18:09 UTC, Lameck1 approved these changes
Hi, @abrormukimov & @blakbox23 

You've done well on this milestone. There are issues I have pointed though, but they will not necessitate requesting for changes since they were not concerns in the first review. Consider your project complete!  It's time to merge it :shipit:

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 18:09 UTC, Lameck1 commented on app.js
> +    removeBook(e.target.previousElementSibling.previousElementSibling.textContent);
- [ ] [OPTIONAL] Try removing books after adding some then check the localStorage, this call to `removeBook` seem not work well with `e.target.previousElementSibling.previousElementSibling.textContent` as an argument. From my testing, the book objects were not deleted at all from the localStorage. You will also realize this when you refresh the page after deleting books, they will all reappear. Look into.

Something like this works for me:

```JavaScript
removeButton.setAttribute('data-title', `${book.title}`);
```

After setting an attribute to the removeButton, I refactor the even listener like this 👇🏼 

```JavaScript
ul.addEventListener('click', (e) => {
  if (e.target.classList.contains('remove-btn')) {
    e.target.parentElement.remove();
    const title = e.target.getAttribute('data-title');
    removeBook(title);
  }
});
```

2021-08-10 18:09 UTC, Lameck1 commented on app.js
> +}
- [ ] [OPTIONAL] Rewriting this can really make your code cleaner: 👇🏼 

```JavaScript
const localstore = JSON.parse(localStorage.getItem('localstore')) || [];
```

2021-08-10 18:09 UTC, Lameck1 commented on app.js
> +});
- [ ] [OPTIONAL] Consider clearing input fields after submitting a new book object to localStorage for good UX.

2021-08-11 08:12 UTC, abrormukimov commented on app.js
> +    removeBook(e.target.previousElementSibling.previousElementSibling.textContent);
Thank you a lot. It is working now)

2021-08-11 08:14 UTC, abrormukimov commented on app.js
> +}
Awesome

2021-08-11 08:20 UTC, abrormukimov commented on app.js
> +});
We did it

2021-08-11 08:22 UTC, merged

2021-08-20 11:23 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

As this feature is still new, there are cases where a request wouldn't be noticed, sadly, yours was one of them, I just noticed this request now, and wanted to apologize for the delay

Thankfully I see that the problem got resolved and you continued with your projects!

Good luck with future projects and keep rocking 🚀!